---
- name: creating cgroup
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: creating cgroup
      raw: cgcreate -a root:root -t root:root -g cpuacct,memory,pids:anisble-runner

...
